/* ALÈ · textos d'interfície · ES · generat per build/publica.js */
window.ALE_T = {
 "t": [
  "Esquema del movimiento",
  "Bajada",
  "Pausa",
  "Subida",
  "3 · última 2",
  "Primera exposición: elige un peso que te deje en la parte baja del rango con el RIR del bloque.",
  "Sesión anterior incompleta: mantén la carga, sin aumento automático.",
  "Sin datos fiables: mantén la carga.",
  "La última vez te quedaste por debajo del rango: mantén o baja la carga.",
  "Falta el RIR en alguna serie: mantén la carga y regístralo hoy.",
  "Techo del rango con el RIR previsto: sube el mínimo incremento disponible (+",
  " kg) y vuelve a la parte baja.",
  "Mantén la carga e intenta sumar 1 repetición respecto a la última vez.",
  "Mesociclo completado",
  "Toca revisar los datos",
  "Genera el informe para el entrenador",
  "Ver la revisión",
  "Siguiente sesión",
  "Ya has entrenado hoy",
  " ejercicios · ",
  " en los principales",
  "Empieza la sesión ",
  "Bloque ",
  "Qué tienes que notar.",
  "Cómo funciona el plan y cada bloque",
  "Cardio · bloque ",
  "Cardio del mesociclo completado",
  "Haz la exposición de cardio",
  "Adherencia del bloque",
  " por lado",
  " · descanso ",
  "Alternativa: ",
  "Plan emitido el ",
  "El plan",
  "Empieza por aquí",
  "Por qué entrenas así",
  "La explicación completa del mesociclo: qué es, qué hace cada bloque, qué significa el RIR, cómo progresa el cardio y qué esperamos al final.",
  "Ver la explicación",
  "ahora",
  " · RIR ",
  "Sesión ",
  "Parejas opcionales para ahorrar tiempo: ",
  "Progresión cardiorrespiratoria",
  "Bloque ",
  "Reglas que no se tocan",
  "Registro del bloque",
  "Progreso",
  "sesiones de fuerza",
  "exposiciones de cardio",
  "Series con todos los datos necesarios según el ejercicio",
  "Última carga por ejercicio",
  "sin datos",
  " kg · ",
  "Historial",
  "Cardio B",
  " · ",
  " · reducida",
  " · parcial",
  " · no completada",
  " · incompleta",
  " · bloque ",
  " · RPE ",
  "Envía los datos",
  "Informe completo del bloque para el entrenador y copia de seguridad del registro.",
  "Informe y copia de seguridad",
  "Revisión de final de bloque",
  "Pasa estos datos al entrenador: adherencia, progresión de carga y repeticiones, respuesta cardiorrespiratoria, dolor y recuperación.",
  "Configuración y datos",
  "Ajustes",
  "Incremento mínimo de carga",
  "Se usa en las sugerencias de progresión",
  "Avisos sonoros",
  "Cambios de intervalo y final del descanso",
  "Activados",
  "Desactivados",
  "Explicación del plan",
  "Cómo funciona el mesociclo y cada bloque",
  "Abrir",
  "Orden de las sesiones",
  "Ahora toca la sesión ",
  " del bloque ",
  "Reloj o banda de FC",
  "Si llevas, la app te pedirá la frecuencia cardíaca al final de cada sesión y de cada cardio",
  "Sí",
  "No",
  "Exporta el bloque para el entrenador o guarda una copia del registro",
  "Tus datos",
  "Todo el registro se guarda en tu dispositivo, dentro de la app. Puedes copiarlo para enviarlo al entrenador o borrarlo cuando quieras. Cuando un ejercicio utilice carga externa, regístrala siguiendo la indicación específica del ejercicio.",
  "Oculta los datos",
  "Copia los datos del bloque",
  "Copiado",
  "Copiado al portapapeles",
  "Se borrarán todas las sesiones, el cardio y las cargas. No se puede deshacer.",
  "Sí, bórralo todo",
  "Cancelar",
  "Borra todo el registro",
  "Sobre esta app",
  "Versión ",
  " · plan emitido el ",
  ". Prescripción inicial de acondicionamiento físico a distancia basada en tu ficha. No es diagnóstico ni tratamiento médico y no sustituye fisioterapia ni una valoración presencial.",
  "Si aparece dolor nuevo de más de 3/10, fiebre, dolor torácico, mareo, desmayo o falta de aire desproporcionada: para y busca valoración sanitaria.",
  "Antes de empezar",
  "Energía",
  "1 vacío · 5 lleno de energía",
  "Dolor ahora mismo",
  "Horas de sueño",
  "Menos de 6 h activa la versión reducida",
  "Síntomas de alarma",
  "Fiebre, dolor torácico, mareo, desmayo, falta de aire desproporcionada o dolor nuevo importante",
  "Hoy tengo poco tiempo",
  "He revisado energía, dolor y sueño",
  "Confirma que los valores de arriba describen cómo estás hoy antes de empezar.",
  "Hoy no entrenas. Si el síntoma es preocupante, busca valoración sanitaria. Mañana vuelve a hacer la comprobación: la sesión ",
  " sigue pendiente y no se pierde.",
  "Entendido",
  "Revisa y confirma los datos",
  "Descanso",
  "Salta",
  "Demostración del ejercicio",
  "Demostración no disponible. Sigue las instrucciones técnicas.",
  "Lateral",
  "Frontal",
  "Vista ",
  "Vista lateral",
  "Sonido activo",
  "Sonido apagado",
  "Reanuda",
  "Tempo ",
  " · segundos de bajada, pausa, subida y pausa",
  "Control · respiración continua",
  "peso corporal",
  "Carga serie ",
  "Segundos",
  "Repeticiones",
  " serie ",
  "RIR serie ",
  "Desmarca",
  "Marca",
  "¿Quieres salir? Los datos de esta sesión que todavía no hayas guardado se perderán.",
  "Calentamiento hecho",
  "Ya he empezado",
  "Empieza la fuerza",
  "Cierra la sesión",
  "series hechas",
  "Sesión reducida",
  "Sesión completa",
  "Sesión parcial",
  "Sesión no completada",
  "Esfuerzo global de la sesión (RPE 1-10)",
  "Cómo te has sentido (motivación 1-5)",
  "1 me ha costado mucho venir · 5 con ganas",
  "Frecuencia cardíaca (opcional)",
  "Media",
  "Máxima",
  "Del reloj o de la banda pectoral. Si hoy no llevabas, déjalo en blanco.",
  "Peso corporal (opcional)",
  "Siempre en condiciones parecidas: al levantarte y antes de desayunar.",
  "Nota breve",
  "Agujetas, molestias, turno de trabajo, sensaciones…",
  "Valora RPE y motivación para guardar",
  "Guarda la sesión",
  "Guarda y haz el cardio ahora",
  "Mantén la variante y suma segundos dentro del rango con posición estable. Cuando llegues al techo con margen, progresa la variante, no fuerces el tiempo.",
  "Mantén la variante y suma repeticiones dentro del rango con control. Progresa el recorrido solo si la zona lumbar se mantiene estable.",
  "Ejercicio ",
  " · sesión ",
  " series × ",
  " reps",
  "Sube carga.",
  "Ajusta a la baja.",
  "Primera vez.",
  "Mantén carga.",
  "Última sesión · ",
  " reps @RIR ",
  " kg × ",
  " @RIR ",
  "Carga",
  "Reps",
  "serie ",
  " de ",
  "Te has quedado por debajo del RIR previsto en alguna serie. Mantén o reduce ligeramente la carga en la siguiente: este bloque no busca el fallo.",
  "Cómo hacerlo bien, paso a paso ",
  "Errores habituales y alternativa ",
  "Alternativa segura.",
  "Opcional: si controlas bien la técnica y quieres acortar la sesión, puedes alternarlo con ",
  "; si no, sigue el orden normal de la app.",
  "Acaba la fuerza",
  "Siguiente · ",
  "verde",
  "amarillo",
  "rojo",
  "datos insuficientes",
  "progresando",
  "retroceso",
  "estable",
  " · dolor ",
  "/10 antes de la sesión ",
  " · día amarillo en la sesión ",
  " parcial: no ha hecho avanzar el plan",
  " no completada",
  " reducida por tiempo",
  " a RIR ",
  " con objetivo ",
  " · dolor relevante en el cardio del bloque ",
  " · posible estancamiento: 3 exposiciones sin mejora detectable",
  " bloqueada por el semáforo rojo",
  "Generado el ",
  " · app v",
  " · plan del ",
  "1. ADHERENCIA Y CARGA GLOBAL",
  "  reducidas por tiempo: ",
  " · parciales: ",
  " · bloqueadas por el semáforo: ",
  " · días amarillos: ",
  "Patrón de cardio alcanzado al final: bloque ",
  " · completado",
  "Duración media: ",
  " min · RPE global medio: ",
  "/10",
  "Motivación media: ",
  "/5 · energía previa: ",
  "/5 · sueño: ",
  " h · dolor: ",
  "Peso corporal: ",
  " kg (",
  ") → ",
  ")",
  "2. DIARIO DE SESIONES",
  "fecha | sesión | bloque | energía/5 | dolor/10 | sueño h | semáforo | RPE | motivación/5 | min | FC med/máx | peso | nota",
  " (parcial)",
  " (no completada)",
  " (reducida)",
  "3. FUERZA POR EJERCICIO (mejor serie de la primera y de la última exposición)",
  "código | ejercicio | tendencia | primera | última | exposiciones | series totales",
  "peso corporal · ",
  " s",
  "carga no registrada",
  " · posible estancamiento",
  "4. CARDIO",
  "fecha | patrón bloque | modalidad | min | RPE | dolor | FC med/máx | completa",
  "sí",
  "5. SEÑALES A REVISAR",
  "Ninguna incidencia registrada.",
  "6. CONTEXTO PARA EL MESOCICLO SIGUIENTE",
  "Documento generado por la app del cliente. Resume el autorregistro de entrenamiento; no es un diagnóstico ni un informe médico.",
  "El navegador ha bloqueado la ventana: descarga el informe y ábrelo.",
  "Restaurar esta copia sustituirá todos los datos actuales de la app. ¿Quieres continuar?",
  "Datos restaurados correctamente",
  "Este fichero no es una copia válida de la app",
  "No se ha podido leer esta copia",
  "Informe y copia",
  "Para el entrenador",
  "Informe completo del bloque: adherencia, recuperación, sesiones, cargas, cardio y señales a revisar. Sirve para decidir el mesociclo siguiente.",
  "Informe copiado: ya lo puedes enviar al entrenador",
  "No se ha podido copiar",
  "Copia el informe",
  "Informe descargado",
  "No se ha podido descargar",
  "Descarga el informe",
  "Imprime o guarda en PDF",
  "Copia de seguridad",
  "Guarda este fichero en tu móvil u ordenador. Si cambias de dispositivo o se borran los datos del navegador, podrás recuperar el progreso. Contiene tu registro de entrenamiento: trátalo como un fichero privado.",
  "Copia guardada en tus ficheros",
  "No se ha podido guardar",
  "Guarda una copia del progreso",
  "Restaura una copia",
  "Oculta la opción avanzada",
  "Opción avanzada: restaurar pegando texto",
  "Pega aquí el contenido JSON de la copia",
  "Restaura este texto",
  "Vista previa del informe",
  "¿Quieres salir? El tiempo de esta exposición que todavía no hayas guardado se perderá.",
  "Exposición detenida",
  "Detén la exposición y no progreses hoy. Valora la causa y busca atención sanitaria si el síntoma es preocupante: dolor agudo, dolor que aumenta, mareo, opresión inusual o falta de aire desproporcionada.",
  "Regístralo y cierra",
  "Cómo ha ido",
  " min",
  "Patrón del bloque ",
  " · versión fácil",
  "Modalidad",
  "Esfuerzo percibido (RPE)",
  "Dolor relevante durante o después",
  "Si lo marcas, no se progresa de bloque",
  "Valora el RPE para guardar",
  "Guarda la exposición",
  "Completa el patrón para guardarla",
  "Guárdala como incompleta",
  " · exposición ",
  "MÁS RITMO",
  "SUAVE",
  "Después: ",
  "más ritmo",
  " ",
  "Último bloque",
  "Empieza",
  "Salta el bloque",
  "Acaba",
  "Para por dolor o síntomas",
  "Entrenamiento personalizado a distancia",
  "Esta app guarda en tu dispositivo lo que registras: energía, horas de sueño, dolor, cargas, repeticiones, RIR y sensaciones. Son datos de salud y los tratamos como tales.",
  "Puedes copiarlos o borrarlos en cualquier momento desde Ajustes. Solo se comparten con el entrenador si tú los envías.",
  "El plan es una prescripción de acondicionamiento físico, no un diagnóstico ni un tratamiento médico, y no sustituye fisioterapia ni una valoración presencial.",
  "Lo entiendo y quiero registrar mi entrenamiento aquí",
  "Empieza el mesociclo",
  "Si aparece dolor nuevo importante, fiebre, dolor torácico, mareo, desmayo o falta de aire desproporcionada: no entrenes y busca valoración sanitaria.",
  "Cargando el plan…",
  "Hoy",
  "Bloque ",
  "Oculta el detalle",
  "Por qué este bloque es así",
  "Qué tienes que notar",
  "Qué tienes que evitar",
  "Cierra",
  "Entendido, empezamos",
  "Continúa",
  " exposiciones",
  "fuerza /",
  "cardio /"
 ]
};
window.ALE_T.f = function (k, p) {
  var s = {
  "repSessions": "Sesiones de fuerza completadas: ${n} de ${tot} (umbral: ${llindar})",
  "repCardio": "Exposiciones de cardio completadas: ${n} de ${tot} (umbral: ${llindar})",
  "repSeries": "Series hechas: ${n} · con todos los datos necesarios según el ejercicio: ${pct}% (umbral: ${llindar}%)",
  "repCap": "${et} · ${s}/${ts} fuerza · ${c}/${tc} cardio",
  "backupAltreClient": "Esta copia es de otro cliente y no se puede restaurar aquí.",
  "errorTitol": "Algo no ha ido bien",
  "errorCos": "La app no se ha podido abrir correctamente. Tus datos siguen guardados en el dispositivo. Avisa al entrenador e indícale el detalle de abajo.",
  "restAra": "Descansar ${s}s",
  "restManual": "descanso de ${ex}"
}[k] || '';
  return s.replace(/\$\{(\w+)\}/g, function (_, n) { return p[n]; });
};
